### ISSUE TITLE
<feature>_enabled? method does not exist

### ISSUE THREAD

**Issue by steijgeler** [nedap/time_pilot#5]
cupido_response_caching is a feature on CareProvider, and the method cupido_response_caching_enabled? should exist. However, it doesn't:

NoMethodError (undefined method `cupido_response_caching_enabled?' for #HealthcareMultiTenant::CareProvider:0x007fd4ce7ea2c0)

**Comment by steijgeler** [comment]
Defining features in multiple TimePilot.configure blocks doesn't work

**Comment by jpleppers** [comment]
Getting the same error for a different feature:

```
undefined method `episodes_enabled?' for #<HealthcareMultiTenant::CareProvider:0x007f9f28c2b720>
```

Restarting the server resolves it. Seems to be the same issue.

**Comment by steijgeler** [comment]
Cleaning up old issues, and this one is probably not relevant anymore
